spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_api
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: none

  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false
